In [44]:
import warnings
warnings.simplefilter('ignore')

In [45]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [46]:
import numpy as np
import pandas as pd

In [47]:
pip install matplotlib

In [48]:
import matplotlib.pyplot as pt

In [49]:
%matplotlib inline

In [50]:
my_data=pd.read_csv("C:\\Users\\arusa\\Downloads\\Admission_Predict.csv")

In [51]:
my_data

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0             1        337          118                  4  4.5   4.5  9.65   
1             2        324          107                  4  4.0   4.5  8.87   
2             3        316          104                  3  3.0   3.5  8.00   
3             4        322          110                  3  3.5   2.5  8.67   
4             5        314          103                  2  2.0   3.0  8.21   
..          ...        ...          ...                ...  ...   ...   ...   
395         396        324          110                  3  3.5   3.5  9.04   
396         397        325          107                  3  3.0   3.5  9.11   
397         398        330          116                  4  5.0   4.5  9.45   
398         399        312          103                  3  3.5   4.0  8.78   
399         400        333          117                  4  5.0   4.0  9.66   

    Research  Chance of Admit   
0        Yes              0.92  
1        Yes              0.76  
2        Yes              0.72  
3        Yes              0.80  
4         No              0.65  
..       ...               ...  
395      Yes              0.82  
396      Yes              0.84  
397      Yes              0.91  
398       No              0.67  
399      Yes              0.95  

[400 rows x 9 columns]

In [52]:
a=my_data.iloc[:,1:6].values
b=my_data.iloc[:,-1].values.reshape(-1,1)


In [53]:
a


array([[337. , 118. ,   4. ,   4.5,   4.5],
       [324. , 107. ,   4. ,   4. ,   4.5],
       [316. , 104. ,   3. ,   3. ,   3.5],
       ...,
       [330. , 116. ,   4. ,   5. ,   4.5],
       [312. , 103. ,   3. ,   3.5,   4. ],
       [333. , 117. ,   4. ,   5. ,   4. ]])

In [54]:
b

array([[0.92],
       [0.76],
       [0.72],
       [0.8 ],
       [0.65],
       [0.9 ],
       [0.75],
       [0.68],
       [0.5 ],
       [0.45],
       [0.52],
       [0.84],
       [0.78],
       [0.62],
       [0.61],
       [0.54],
       [0.66],
       [0.65],
       [0.63],
       [0.62],
       [0.64],
       [0.7 ],
       [0.94],
       [0.95],
       [0.97],
       [0.94],
       [0.76],
       [0.44],
       [0.46],
       [0.54],
       [0.65],
       [0.74],
       [0.91],
       [0.9 ],
       [0.94],
       [0.88],
       [0.64],
       [0.58],
       [0.52],
       [0.48],
       [0.46],
       [0.49],
       [0.53],
       [0.87],
       [0.91],
       [0.88],
       [0.86],
       [0.89],
       [0.82],
       [0.78],
       [0.76],
       [0.56],
       [0.78],
       [0.72],
       [0.7 ],
       [0.64],
       [0.64],
       [0.46],
       [0.36],
       [0.42],
       [0.48],
       [0.47],
       [0.54],
       [0.56],
       [0.52],
       [0.55],
       [0.

In [55]:
pip install scikit-learn

Note: you may need to restart the kernel to use updated packages.


In [56]:
from sklearn.model_selection import train_test_split

In [57]:
a_train,a_test,b_train,b_test=train_test_split(a,b,test_size=0.3 ,random_state=0)

In [58]:
a_test

array([[309. , 105. ,   5. ,   3.5,   3.5],
       [308. , 110. ,   4. ,   3.5,   3. ],
       [326. , 110. ,   3. ,   3.5,   3.5],
       [306. , 105. ,   2. ,   3. ,   2.5],
       [316. , 105. ,   3. ,   3. ,   3.5],
       [309. , 100. ,   2. ,   3. ,   3. ],
       [312. , 109. ,   3. ,   3. ,   3. ],
       [312. , 104. ,   3. ,   3.5,   4. ],
       [332. , 118. ,   2. ,   4.5,   3.5],
       [331. , 117. ,   4. ,   4.5,   5. ],
       [300. , 105. ,   1. ,   1. ,   2. ],
       [333. , 113. ,   5. ,   4. ,   4. ],
       [320. , 110. ,   2. ,   4. ,   3.5],
       [302. ,  99. ,   1. ,   2. ,   2. ],
       [328. , 112. ,   4. ,   4. ,   4.5],
       [311. , 104. ,   2. ,   2. ,   2. ],
       [312. ,  98. ,   1. ,   3.5,   3. ],
       [329. , 110. ,   2. ,   4. ,   3. ],
       [315. ,  99. ,   2. ,   3.5,   3. ],
       [313. , 107. ,   3. ,   4. ,   4.5],
       [329. , 119. ,   4. ,   4.5,   4.5],
       [327. , 113. ,   4. ,   4.5,   5. ],
       [301. , 106. ,   4. ,   2

In [59]:
from sklearn.linear_model import LinearRegression

In [60]:
lm=LinearRegression()

In [61]:
lm.fit(x_train,y_train)

LinearRegression()

In [62]:
Ypredict=lm.predict(a_test)

In [63]:
Ypredict

array([[0.70042165],
       [0.69149507],
       [0.78660476],
       [0.60699342],
       [0.70672563],
       [0.61216664],
       [0.69095423],
       [0.69978199],
       [0.8501902 ],
       [0.91984394],
       [0.5392704 ],
       [0.88552157],
       [0.74360388],
       [0.51928293],
       [0.8581111 ],
       [0.6065514 ],
       [0.60393037],
       [0.77192489],
       [0.63863136],
       [0.74031845],
       [0.90322561],
       [0.87745119],
       [0.63093748],
       [0.47961563],
       [0.77842225],
       [0.5868472 ],
       [0.4835463 ],
       [0.66307178],
       [0.92978916],
       [0.6910364 ],
       [0.64895342],
       [0.7548102 ],
       [0.7331453 ],
       [0.52160347],
       [0.80646713],
       [0.78379714],
       [0.7288511 ],
       [0.83818511],
       [0.62694165],
       [0.89653954],
       [0.74972283],
       [0.70965835],
       [0.77167099],
       [0.81020752],
       [0.84757071],
       [0.76480393],
       [0.64987693],
       [0.740

In [64]:
comparison=pd.DataFrame(a_test,columns=["input data","input data1","input data2","input data3","input data4"])

In [65]:
comparison["AVL_o/p"]=b_test

In [66]:
comparison

input data  input data1  input data2  input data3  input data4  AVL_o/p
0         309.0        105.0          5.0          3.5          3.5     0.71
1         308.0        110.0          4.0          3.5          3.0     0.70
2         326.0        110.0          3.0          3.5          3.5     0.79
3         306.0        105.0          2.0          3.0          2.5     0.73
4         316.0        105.0          3.0          3.0          3.5     0.72
..          ...          ...          ...          ...          ...      ...
115       322.0        112.0          4.0          4.5          4.5     0.91
116       331.0        119.0          4.0          5.0          4.5     0.90
117       327.0        111.0          4.0          3.0          4.0     0.78
118       310.0        104.0          3.0          2.0          3.5     0.70
119       305.0        103.0          2.0          2.5          3.5     0.59

[120 rows x 6 columns]

In [67]:
comparison["PRE_o/p"]=Ypredict

In [68]:
comparison

input data  input data1  input data2  input data3  input data4  AVL_o/p  \
0         309.0        105.0          5.0          3.5          3.5     0.71   
1         308.0        110.0          4.0          3.5          3.0     0.70   
2         326.0        110.0          3.0          3.5          3.5     0.79   
3         306.0        105.0          2.0          3.0          2.5     0.73   
4         316.0        105.0          3.0          3.0          3.5     0.72   
..          ...          ...          ...          ...          ...      ...   
115       322.0        112.0          4.0          4.5          4.5     0.91   
116       331.0        119.0          4.0          5.0          4.5     0.90   
117       327.0        111.0          4.0          3.0          4.0     0.78   
118       310.0        104.0          3.0          2.0          3.5     0.70   
119       305.0        103.0          2.0          2.5          3.5     0.59   

      PRE_o/p  
0    0.700422  
1    0.691495  
2    0.786605  
3    0.606993  
4    0.706726  
..        ...  
115  0.829038  
116  0.914852  
117  0.827145  
118  0.667788  
119  0.624364  

[120 rows x 7 columns]